<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Utilisateur;

/**
 * AchievementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchievementRepository extends \Doctrine\ORM\EntityRepository
{


    public function getLockedAchievementsFor(Utilisateur $utilisateur){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $achievements = $qb->select('achievement')
            ->from('AppBundle:Achievement', 'achievement')
            ->getQuery()
            ->getArrayResult();
        var_dump($achievements);
        die();
    }

    public function getUnlockedAchievementsFor(Utilisateur $utilisateur){
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb->select('achievement')
            ->from('AppBundle:Achievement', 'achievement')
            ->innerJoin('achievement.userAchievementsAssociation', 'userAchievementsAssociation')
            ->where('userAchievementsAssociation.utilisateur = :user')
            ->setParameter('user', $utilisateur)
            ->andWhere('userAchievementsAssociation.unlockedAt IS NOT NULL')
            ->getQuery()
            ->getResult();
    }
}
