<?php

namespace AppBundle\Repository;
use AppBundle\Entity\TutorielPage;

/**
 * TutorielPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorielPageRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $number
     * @return TutorielPage[]
     */
    public function findAllSuperiorToPage($number){
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb->select('tutorielPage')
            ->from('AppBundle:TutorielPage', 'tutorielPage')
            ->where($qb->expr()->gt('tutorielPage.pageNumber', $number))
            ->getQuery()->getResult();
    }

}
