<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Tutoriel;

/**
 * TutorielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorielRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $number
     * @return Tutoriel[]
     */
    public function getFirstNth($number) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb->select('tutoriel')
            ->from('AppBundle:Tutoriel', 'tutoriel')
            ->setMaxResults($number)
            ->getQuery()
            ->getResult();
    }

}
