<?php

namespace AppBundle\Repository;

/**
 * TutorielPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorielPageRepository extends \Doctrine\ORM\EntityRepository
{
}
