<?php

namespace AppBundle\Repository;

/**
 * UserProgressionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProgressionRepository extends \Doctrine\ORM\EntityRepository
{
}
