<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Utilisateur;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * @param $r
     * @return Utilisateur[]
     */
    public function findByRole($r) {
        $role = $this->getEntityManager()->getRepository('AppBundle:Role')->findOneBy(['role' => $r]);
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb->select('utilisateur')
            ->from('AppBundle:Utilisateur', 'utilisateur')
            ->innerJoin('utilisateur.roles', 'roles')
            ->where('roles = :roles')
            ->setParameter('roles', $role)
            ->getQuery()
            ->getResult();

    }


}
