# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    always_authenticate_before_granting: true

    access_control: ~


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        User:
            entity:
                class: AppBundle:Utilisateur
                property: username

    encoders:
        AppBundle\Entity\Utilisateur:
            algorithm: bcrypt


    role_hierarchy:
        ROLE_WRITER:      ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            provider: User
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /
                success_handler: logout_success_handler
                invalidate_session: false

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html


