# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public: false
        arguments:
            - '%database_dsn%:host=%database_host%;port=%database_port%;dbname=%database_name%'
            - { db_table: sessions, db_username: '%database_user%', db_password: '%database_password%' }

    app.security.role_change_listener:
        class: AppBundle\RoleListener
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@security.token_storage'

    app.twig_extension:
      class: AppBundle\Twig\AppExtension
      public: false
      tags:
        - { name: twig.extension }

    app.utils:
        class: AppBundle\Utils
        arguments: ['@swiftmailer.mailer', '@doctrine.orm.entity_manager', '@service_container']

    security.authentication.success_handler:
        class: AppBundle\Handler\AuthenticationSuccessHandler
        arguments: ['@security.http_utils', '@service_container', {}]
        tags:
            - { name: 'monolog.logger', channel: 'security'}

    kernel.listener.finished.tutoriel:
        class: AppBundle\Events\TutorielListener
        tags:
            - { name: kernel.event_listener, event: tutoriel.finished, method: onFinishedTutoriel }

    logout_success_handler:
        class: AppBundle\Handler\LogoutSuccessHandler
        arguments: ['@security.http_utils', '@service_container']

    tutoriel.namer:
        class: AppBundle\Namer\TutorielNamer
